### ISSUE TITLE
"Cutegram newsletter"

### ISSUE THREAD

**Issue by AndrewRi** [Aseman-Land/Cutegram#243]
When switching "Cutegram newsletter" crash program

**Comment by ignatenkobrain** [comment]
```
#0  0x00007fffc5ba42bd in TelegramPeerDetails::setJoined(bool) (this=0x555556ac53c0, joined=<optimized out>) at ../telegrampeerdetails.cpp:344
        inputUser = 
          {<TelegramTypeObject> = {_vptr.TelegramTypeObject = 0x7fffc5f89880 <vtable for InputUser+16>, static null = {<No data fields>}, mError = false, mNull = false}, m_accessHash = 0, m_userId = -1488372224, m_classType = InputUser::typeInputUser}
        tg = <optimized out>
        dis = {wp = {d = 0x55555797fe50, value = 0x7ffff7b31da6 <QSGAreaAllocator::allocateInNode(QSize const&, QPoint&, QRect const&, QSGAreaAllocatorNode*)+214>}}
#1  0x00007fffc5c646b2 in TelegramPeerDetails::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=_o@entry=0x555556ac53c0, _c=_c@entry=QMetaObject::WriteProperty, _id=_id@entry=14, _a=_a@entry=0x7fffffff9150) at moc_telegrampeerdetails.cpp:408
        _t = 0x555556ac53c0
        _v = <optimized out>
#2  0x00007fffc5c6609b in TelegramPeerDetails::qt_metacall(QMetaObject::Call, int, void**) (this=0x555556ac53c0, _c=QMetaObject::WriteProperty, _id=14, _a=0x7fffffff9150)
    at moc_telegrampeerdetails.cpp:452
#3  0x00007ffff6d2b522 in QQmlPropertyPrivate::write(QObject*, QQmlPropertyData const&, QVariant const&, QQmlContextData*, QFlags<QQmlPropertyPrivate::WriteFlag>) (object=object@entry=0x555556ac53c0, property=..., value=..., context=0x555559a2c700, flags=...) at /usr/src/debug/qtdeclarative-opensource-src-5.7.0/src/qml/qml/qqmlproperty.cpp:1259
        a = {0x7fffffff91e0, 0x0, 0x7fffffff90bc, 0x7fffffff90a0}
        coreIdx = 18
        status = -1
        propertyType = 1
        variantType = <optimized out>
#4  0x00007ffff6cf79f3 in QV4::QObjectWrapper::setProperty(QV4::ExecutionEngine*, QObject*, QQmlPropertyData*, QV4::Value const&) (engine=0x5555564c9290, object=0x555556ac53c0, property=0x7fffcc284428, value=...) at /usr/src/debug/qtdeclarative-opensource-src-5.7.0/src/qml/jsruntime/qv4qobjectwrapper.cpp:544
        v = 
            {d = {data = {c = 1 '\001', uc = 1 '\001', s = -26879, sc = 1 '\001', us = 38657, i = 1468569345, u = 1468569345, l = 93825029150465, ul = 93825029150465, b = true, d = 4.6355723623298274e-310, f = 3.00364276e+14, real = 4.6355723623298274e-310, ll = 93825029150465, ull = 93825029150465, o = 0x555557889701, ptr = 0x555557889701, shared = 0x555557889701}, type = 1, is_shared = 0, is_null = 0}}
        callingQmlContext = <optimized out>
        newBinding = <optimized out>
        scope = {engine = 0x5555564c9290, mark = 0x7fffdc63c4a8}
#5  0x00007ffff6d0e3af in QV4::Runtime::setQmlQObjectProperty(QV4::ExecutionEngine*, QV4::Value const&, int, QV4::Value const&) (engine=0x5555564c9290, object=..., propertyIndex=<optimized out>, value=...) at /usr/src/debug/qtdeclarative-opensource-src-5.7.0/src/qml/jsruntime/qv4runtime.cpp:1488
#6  0x00007fffc309c49c in  ()
#7  0x0000000000000764 in  ()
#8  0x0000004300001fff in  ()
#9  0x0000000000000000 in  ()
```
